// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqG-Tbz68XlaWlIP969fqmR7AeoRa0qbI',
    appId: '1:357333755818:web:e422326598f43869262dd3',
    messagingSenderId: '357333755818',
    projectId: 'chat-app-301d5',
    authDomain: 'chat-app-301d5.firebaseapp.com',
    databaseURL: 'https://chat-app-301d5-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-301d5.appspot.com',
    measurementId: 'G-NP6YES689G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0crRubPR6vZTPHrLqkRqKvepofcujUdQ',
    appId: '1:357333755818:android:7c99216ee2245e3c262dd3',
    messagingSenderId: '357333755818',
    projectId: 'chat-app-301d5',
    databaseURL: 'https://chat-app-301d5-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-301d5.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqG-Tbz68XlaWlIP969fqmR7AeoRa0qbI',
    appId: '1:357333755818:web:45bf4f88f6c843d4262dd3',
    messagingSenderId: '357333755818',
    projectId: 'chat-app-301d5',
    authDomain: 'chat-app-301d5.firebaseapp.com',
    databaseURL: 'https://chat-app-301d5-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-301d5.appspot.com',
    measurementId: 'G-J8QV2LRPDX',
  );
}
